#!/usr/bin/env python3

import glob
import os
import sys

from yattag.doc import Doc
from pathlib import Path


IMG_PATH = "images"
IMG_TYPES = [".jpg", ".jpeg", ".png", ".gif"]
VID_TYPES = [".mp4"]


def is_media(path: Path) -> bool:
    return path.suffix.lower() in (IMG_TYPES + VID_TYPES)


doc, tag, text = Doc().tagtext()


with tag("html"):
    with tag("head"):
        doc.stag('meta', charset="UTF-8")
        doc.stag("link", rel="stylesheet", href="style.css")
    with tag("body"):
        with tag("center"):

            dirs = glob.glob(IMG_PATH + "/*")
            dirs.sort(key=os.path.basename, reverse=True)

            len_dirs = len(dirs)
            for i, dname in enumerate(dirs):

                with tag("h2"):
                    text(dname[10:])  # Strip images/xxx where xxx is a number

                for fname in sorted(os.listdir(dname)):

                    fpath = Path(dname) / Path(fname)
                    if is_media(fpath):
                        print(f"Found {fpath}")
                        with tag("div", id='photo-container',
                                 style="margin-bottom:3mm; margin-top:3mm"):
                            with tag("a", href=str(fpath)):
                                if fpath.suffix.lower() in IMG_TYPES:
                                    doc.stag('img', src=str(fpath), width=700)
                                if fpath.suffix.lower() in VID_TYPES:
                                    with tag("video", controls='', loop=True, width=700):
                                        doc.stag('source', src=str(fpath))

                if i < len_dirs - 1:
                    doc.stag("hr", klass="solid")

result = doc.getvalue()

out_index = sys.argv[1]

with open(out_index, "w") as f:
    f.write(result)
