#!/usr/bin/env python3

import glob
import os
import sys

from yattag import Doc
from pathlib import Path


IMG_PATH = "images"


def is_img(path: Path) -> bool:
    accepted = (".jpg", ".jpeg", ".png", ".gif")
    return path.suffix.lower() in accepted


doc, tag, text = Doc().tagtext()


with tag("html"):
    with tag("head"):
        doc.stag('meta', charset="UTF-8")
    with tag("body"):
        with tag("center"):

            dirs = glob.glob(IMG_PATH + "/*")
            dirs.sort(key=os.path.getmtime, reverse=True)

            for dname in dirs:

                with tag("h2"):
                    text(dname[7:])  # Strip images/

                for fname in os.listdir(dname):

                    fpath = Path(dname) / Path(fname)
                    if is_img(fpath):
                        print(f"Found image {fpath}")
                        with tag('div', id='photo-container',
                                 style="margin-bottom:3mm; margin-top:3mm"):
                            doc.stag('img', src=str(fpath), width=700)

result = doc.getvalue()

out_index = sys.argv[1]

with open(out_index, "w") as f:
    f.write(result)
